version: '3.1'
networks:
    study_network:
        ipam:
            config:
                - subnet: 100.10.0.0/16

services:
    mysql:
        image: 'mysql:5.7'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=rootpass
            - MYSQL_DATABASE=study
            - MYSQL_USER=user
            - MYSQL_PASSWORD=userpass
        ports:
            - '53002:3306'
        networks:
            study_network:
                ipv4_address: 100.10.0.11

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '53000:80'
        networks:
            study_network:
                ipv4_address: 100.10.0.12

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
        networks:
            study_network:
                ipv4_address: 100.10.0.13
